# Generated by Django 4.2.29 on 2026-04-04 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (always positive).",
                        max_digits=14,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        help_text="Income or Expense.",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("investment", "Investment"),
                            ("freelance", "Freelance"),
                            ("rent", "Rent"),
                            ("utilities", "Utilities"),
                            ("food", "Food & Dining"),
                            ("transport", "Transport"),
                            ("healthcare", "Healthcare"),
                            ("entertainment", "Entertainment"),
                            ("education", "Education"),
                            ("tax", "Tax"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_records",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
