# Generated by Django 4.2.29 on 2026-04-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["transaction_type"], name="financial_r_transac_80c6b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["category"], name="financial_r_categor_2871f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(fields=["date"], name="financial_r_date_c7ef46_idx"),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["is_deleted"], name="financial_r_is_dele_213f2d_idx"
            ),
        ),
    ]
